package com.notifyhub.dto;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Immutable DTO for order events exchanged via RabbitMQ.
 * Uses Java record for conciseness.
 *
 * @param orderId  UUID of the order (generated by producer)
 * @param userId   identifier of the user who placed the order
 * @param amount   total order amount
 * @param status   initial order status
 */
public record OrderEventDto(
        UUID orderId,
        String userId,
        BigDecimal amount,
        String status
) {
}
